# Generated by Django 3.2.7 on 2021-09-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_img_name', models.CharField(max_length=100)),
                ('cap_date', models.DateTimeField(verbose_name='date captured')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_img_name', models.CharField(max_length=100)),
                ('ori_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.originalimage')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_img_name', models.CharField(max_length=100)),
                ('det_json_name', models.BooleanField(default=False)),
                ('ori_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.originalimage')),
            ],
        ),
    ]
