# Generated by Django 3.2.7 on 2021-09-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_img_name', models.CharField(max_length=100)),
                ('det_json_name', models.BooleanField(default=False)),
                ('det_img', models.ImageField(upload_to='images/', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_img_name', models.CharField(max_length=100)),
                ('seg_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='ori_img',
        ),
        migrations.AddField(
            model_name='originalimage',
            name='org_img',
            field=models.ImageField(default='', upload_to='images/', verbose_name='img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='Segmentation',
        ),
        migrations.AddField(
            model_name='segmentationimage',
            name='ori_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.originalimage'),
        ),
        migrations.AddField(
            model_name='detectionimage',
            name='ori_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.originalimage'),
        ),
    ]
