# Generated by Django 3.2.7 on 2021-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20210921_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationimage',
            name='seg_img',
            field=models.ImageField(upload_to='images/', verbose_name='img'),
        ),
    ]
