# Generated by Django 3.2.7 on 2021-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20210921_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionimage',
            name='det_img',
            field=models.ImageField(upload_to='Flights/'),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='org_img',
            field=models.ImageField(upload_to='Flights/'),
        ),
        migrations.AlterField(
            model_name='segmentationimage',
            name='seg_img',
            field=models.ImageField(upload_to='Flights/'),
        ),
    ]
